In [ ]:
import numpy as np
import cv2 as cv
import matplotlib.pyplot as plot



#cap = cv.VideoCapture(0)



face_cascade = cv.CascadeClassifier('haarcascade_frontalface_default.xml')
eye_cascade = cv.CascadeClassifier('haarcascade_eye.xml')
img = cv.imread(r'F:\data\2.jpg')
gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
print(img)

faces = face_cascade.detectMultiScale(gray, 1.3, 5)

for (x,y,w,h) in faces:
    cv.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
    roi_gray = gray[y:y+h, x:x+w]
    roi_color = img[y:y+h, x:x+w]
    eyes = eye_cascade.detectMultiScale(roi_gray)
    i=1
    for (ex,ey,ew,eh) in eyes:
        cv.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)
    # roi = img[y:y + height, x:x + width]
        roi = roi_color[ey:ey+eh, ex:ex+ew ]       #按照脸这张图的为大坐标的基础上截的 因为眼睛一点在脸上～
        cv.imwrite(str(i)+"roi.jpg", roi)           #两个眼睛所以设置不同的i保存的图片名字不一样
        i=i+1
        print(roi)

cv.imshow('img',img)
cv.waitKey(0)
cv.destroyAllWindows()


[[[ 66  73  76]
  [ 67  76  79]
  [ 69  78  81]
  ...
  [ 89  97 110]
  [108 111 116]
  [117 112 113]]

 [[ 70  77  80]
  [ 70  79  82]
  [ 71  80  83]
  ...
  [ 77  85  98]
  [100 102 110]
  [112 110 110]]

 [[ 73  80  83]
  [ 74  81  84]
  [ 73  82  85]
  ...
  [ 70  79  92]
  [ 95  98 106]
  [114 112 112]]

 ...

 [[137 123 105]
  [139 125 106]
  [135 124 102]
  ...
  [ 47  49  49]
  [ 49  49  49]
  [ 57  57  57]]

 [[136 122 104]
  [137 123 104]
  [134 123 101]
  ...
  [ 47  49  49]
  [ 48  48  48]
  [ 55  55  55]]

 [[135 121 103]
  [132 121 101]
  [127 118  98]
  ...
  [ 47  49  49]
  [ 48  48  48]
  [ 54  54  54]]]


In [ ]:
import cv2 as cv
import numpy as np

pathj = 'F:\\data\\628.jpg'
pathf = 'F:\\data\\haarcascade_frontalface_default.xml'
pathe = 'F:\\data\\haarcascade_eye.xml'

face_cascade = cv.CascadeClassifier(pathf)
#face_cascade.load(pathf)
eye_cascade = cv.CascadeClassifier(pathe)
#eye_cascade.load(pathe)
img = cv.imread(pathj)
gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)

faces = face_cascade.detectMultiScale(gray,1.1,3)
#print(faces)
for(x,y,w,h) in faces:
    cv.rectangle(img,(x,y),(x+w,x+h),(255,0,0),2)
    face_re = img[y:y+h, x:x+h]
    face_re_g=gray[y:y+h, x:x+h]
    eyes = eye_cascade.detectMultiScale(face_re_g)
    for(ex,ey,ew,eh) in eyes:
        cv.rectangle(face_re,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)

cv.imshow('img',img)
cv.waitKey(0)
cv.destroyAllWindows()



In [ ]:
feces